# Generated by Django 5.1.6 on 2025-02-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['distance_km']},
        ),
        migrations.RenameField(
            model_name='route',
            old_name='distance',
            new_name='distance_km',
        ),
    ]
