# Generated by Django 5.1.6 on 2025-02-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_crew_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='traintype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
