# Generated by Django 5.1.6 on 2025-02-22 20:16

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_traintype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.create_custom_path),
        ),
    ]
