# Generated by Django 5.1.6 on 2025-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_train_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.IntegerField()),
                ('user_ip', models.GenericIPAddressField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
